name: Node.js CI

on:
  push: 
    branches: [ main ]


jobs: 
  build_main: 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Checkout   
      uses: actions/checkout@v2
      with: 
        persist-credentials: true
        submodules: recursive
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - run: npm install
    
    - run: npm run build
      env:
        CI: true
        GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
        GOOGLE_SHEET_KEY: ${{ secrets.GOOGLE_SHEET_KEY}}
        GOOGLE_ID: ${{secrets.GOOGLE_ID}}
   
    - name: Deploy to prod branch
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: PRODUCTION # The branch the action should deploy to.
        FOLDER: dist # The folder the action should deploy.
        CLEAN: true # Automatically remove deleted files from the deploy branch